task 10
Abdelwahab-IO/cost-of-living pull request #2
Opened 2023-02-11 21:42 UTC by ZeyadAbdullah679

setup the class and testing class 
adding package test with tests classes for every case

2023-02-11 22:33 UTC, AbdelrahmanMohamed-m approved these changes

2023-02-12 18:07 UTC, Abdelwahab-IO commented on src/main/kotlin/interactor/GetTheMostSuitableCityForSavingMoneyWhileAccommodation.kt
> +    fun execute(): String {
function must return city entity instead of string as mentioned in requirements

2023-02-12 18:08 UTC, Abdelwahab-IO commented on src/main/kotlin/interactor/GetTheMostSuitableCityForSavingMoneyWhileAccommodation.kt
> +) {
function must return city entity instead of string as mentioned in requirements

2023-02-12 18:18 UTC, Abdelwahab-IO requested changes
you can merge all this fake data into one file that have a multiple classes or make a one class that holds the whole fake data

2023-02-12 18:18 UTC, Abdelwahab-IO commented on src/main/kotlin/interactor/GetTheMostSuitableCityForSavingMoneyWhileAccommodation.kt
> +        } else {
try to make a helper function for this code

2023-02-12 18:18 UTC, Abdelwahab-IO commented on src/main/kotlin/interactor/GetTheMostSuitableCityForSavingMoneyWhileAccommodation.kt
> +) {
function must return city entity instead of string as mentioned in requirements

2023-02-12 18:18 UTC, Abdelwahab-IO commented on src/test/kotlin/interactor/GetTheMostSuitableCityForSavingMoneyWhileAccommodationTest.kt
> +
low quality data is the data with null values any way so merge low quality and null data in one case and name it low quality data

2023-02-12 18:18 UTC, Abdelwahab-IO commented on src/test/kotlin/interactor/GetTheMostSuitableCityForSavingMoneyWhileAccommodationTest.kt
> +
use `@BeforeAll` instead of `@BeforeEach` annotation

2023-02-12 18:18 UTC, Abdelwahab-IO commented on src/test/kotlin/interactor/GetTheMostSuitableCityForSavingMoneyWhileAccommodationTest.kt
> +package interactor
make the required changes in this test class to make it suitable for testing the new imp of your interactor class

2023-02-12 23:35 UTC, Abdelwahab-IO commented on src/main/kotlin/interactor/GetTheMostSuitableCityForSavingMoneyWhileAccommodation.kt
> +) {
`minOf(a?:Float.MAX_VALUE,b?: Float.MAX_VALUE)`

2023-02-13 13:35 UTC, ZeyadAbdullah679 commented on src/test/kotlin/interactor/GetTheMostSuitableCityForSavingMoneyWhileAccommodationTest.kt
> +
gives me runtime error when testing

2023-02-13 13:37 UTC, ZeyadAbdullah679 commented
I have changed the code so review and tell me

2023-02-13 18:44 UTC, Abdelwahab-IO approved these changes
good job

2023-02-13 18:45 UTC, merged